[package]
name = "nunjack"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[dependencies]
clap = { version = "4.4.8", default-features = false, features = ["std", "help", "derive"] }
nunjack-core = { path = "nunjack-core" }
