---
name: Publish Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-target:
          - toolchain: stable
            target: aarch64-unknown-linux-gnu
          - toolchain: stable
            target: x86_64-unknown-linux-gnu
          - toolchain: stable
            target: x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install rust
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
        with:
          toolchain: ${{ matrix.build-target.toolchain }}
          profile: minimal
          override: true
          target: ${{ matrix.build-target.target }}
      - name: Build Target
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.1
        with:
          use-cross: true
          command: build
          args: --release --bin nunjack --target ${{ matrix.build-target.target }}
      - name: Package
        run: |-
          mv target/${{ matrix.build-target.target}}/release/nunjack nunjack-${{ matrix.build-target.target }}
      - name: Publish
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: 'nunjack-*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
